language: rust
os: linux

rust:
  - stable
  - beta
  - nightly
  - 1.30.0

script:
  - cargo test --all

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false
