language: rust
os: linux

rust:
  - stable
  - beta
  - nightly
  - 1.24.0

script:
  - cargo test --all

matrix:
  include:
    - rust: 1.20.0
      script:
        - cargo build
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false
