[package]
name = "nl80211"
version = "0.1.0"
authors = ["Erik Svensson <erik.public@gmail.com>"]
build = "build.rs"
description="Experiments with netlink and nl80211 in Rust"
license="MIT"
repository="https://github.com/blueluna/nl80211-rs"
keywords = ["netlink", "nl80211", "80211"]

[workspace]
members = ["netlink-buildtools", "netlink"]

[build-dependencies]
netlink-buildtools = { version="0.1", path="netlink-buildtools" }

[dependencies]
libc = "0.2"
netlink = { version="0.1", path="netlink" }

[dev-dependencies]
mio = "0.6"
clap = "2"
